var address = "0xc3a422E816444341Fcc88dCec9bc9462266be969";


var abi = [{"outputs": [], "inputs": [], "constant": false, "payable": false, "type": "constructor"}, {"name": "initiate", "outputs": [], "inputs": [{"type": "address", "name": "token_addr"}, {"type": "uint256", "name": "token_quantity", "unit": "a currency"}], "constant": false, "payable": true, "type": "function", "gas": 178732}, {"name": "ethToTokens", "outputs": [], "inputs": [], "constant": false, "payable": true, "type": "function", "gas": 110704}, {"name": "tokensToEth", "outputs": [], "inputs": [{"type": "uint256", "name": "sell_quantity", "unit": "a currency"}], "constant": false, "payable": false, "type": "function", "gas": 109216}, {"name": "estimateETT", "outputs": [{"type": "uint256", "name": "out", "unit": "a currency"}], "inputs": [{"type": "uint256", "name": "_value", "unit": "wei"}], "constant": true, "payable": false, "type": "function", "gas": 2741}, {"name": "estimateTTE", "outputs": [{"type": "uint256", "name": "out", "unit": "wei"}], "inputs": [{"type": "uint256", "name": "sell_quantity", "unit": "a currency"}], "constant": true, "payable": false, "type": "function", "gas": 2069}, {"name": "setOwner", "outputs": [], "inputs": [{"type": "address", "name": "new"}], "constant": false, "payable": false, "type": "function", "gas": 35777}, {"name": "getfeebal", "outputs": [{"type": "uint256", "name": "out", "unit": "wei"}], "inputs": [], "constant": false, "payable": false, "type": "function", "gas": 956}, {"name": "cashfeebal", "outputs": [], "inputs": [], "constant": false, "payable": true, "type": "function", "gas": 55893}, {"name": "setFee", "outputs": [], "inputs": [{"type": "uint256", "name": "new_fee"}], "constant": false, "payable": false, "type": "function", "gas": 35828}, {"name": "ownerWithdraw", "outputs": [], "inputs": [], "constant": false, "payable": false, "type": "function", "gas": 28805}, {"name": "totalEthQty", "outputs": [{"type": "uint256", "name": "out", "unit": "wei"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 783}, {"name": "totalTokenQty", "outputs": [{"type": "uint256", "name": "out", "unit": "a currency"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 813}, {"name": "invariant", "outputs": [{"type": "uint256", "name": "out", "unit": "a currency-wei"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 843}, {"name": "owner", "outputs": [{"type": "address", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 873}, {"name": "fee", "outputs": [{"type": "uint256", "name": "out"}], "inputs": [], "constant": true, "payable": false, "type": "function", "gas": 903}];

dex = web3.eth.contract(abi).at(address);		
			
alert("Imported DEX");




